# Generated by Django 2.1.15 on 2020-01-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('MOBILE', models.IntegerField(max_length=10)),
                ('ACCESS_STATUS', models.BooleanField(default=False)),
            ],
        ),
    ]
