# Generated by Django 2.1.15 on 2020-01-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='MOBILE',
            field=models.CharField(max_length=10),
        ),
    ]
