# Generated by Django 2.2.6 on 2020-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200109_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(default='NA', max_length=110)),
                ('LEAVE_TYPE', models.CharField(max_length=100)),
                ('LEAVE_START', models.DateField()),
                ('LEAVE_END', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(default='NA', max_length=100)),
                ('TOTAL_ANNUAL_LEAVES', models.IntegerField()),
                ('TOTAL_SICK_LEAVES', models.IntegerField()),
                ('TOTAL_WFH', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SickLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(default='NA', max_length=110)),
                ('LEAVE_TYPE', models.CharField(max_length=100)),
                ('LEAVE_START', models.DateField()),
                ('LEAVE_END', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkFromHomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(default='NA', max_length=110)),
                ('WFH_TYPE', models.CharField(max_length=100)),
                ('WFH_START', models.DateField()),
                ('WFH_END', models.DateField()),
                ('WFH_ADDRESS', models.CharField(max_length=100)),
            ],
        ),
    ]
